# Generated by Django 4.2.7 on 2025-06-23 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maisons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('taille', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('appartement', 'Appartement'), ('maison', 'Maison')], max_length=20)),
                ('meublee', models.BooleanField(default=False)),
                ('salle_de_bain', models.BooleanField(default=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='maisons.maison')),
            ],
        ),
    ]
