# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chambres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('statut', models.CharField(max_length=20, choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_locataire', to=settings.AUTH_USER_MODEL)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='chambres.chambre')),
            ],
        ),
    ] 