# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(max_digits=10, decimal_places=2)),
                ('statut', models.CharField(max_length=10, choices=[('paye', 'Payé'), ('impaye', 'Impayé')], default='impaye')),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='contrats.contrat')),
            ],
        ),
    ] 