# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chambres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_caution', models.DecimalField(max_digits=10, decimal_places=2)),
                ('mois_caution', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('mode_paiement', models.CharField(max_length=20, choices=[('cash', 'Cash'), ('virement', 'Virement'), ('mobile money', 'Mobile Money')])),
                ('periodicite', models.CharField(max_length=20, choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel')])),
                ('statut', models.CharField(max_length=10, choices=[('actif', 'Actif'), ('resilie', 'Résilié')], default='actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_locataire', to=settings.AUTH_USER_MODEL)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='chambres.chambre')),
            ],
        ),
    ] 