# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('chambres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('type', models.CharField(max_length=10, choices=[('photo', 'Photo'), ('video', 'Vidéo')])),
                ('description', models.TextField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='chambres.chambre')),
            ],
        ),
    ] 