# Generated by Django 4.2.7 on 2025-07-05 23:15

import apps.medias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.medias.models.media_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
