# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20, choices=[('plomberie', 'Plomberie'), ('electricite', 'Électricité'), ('autre', 'Autre')])),
                ('responsable', models.CharField(max_length=20, choices=[('locataire', 'Locataire'), ('proprietaire', 'Propriétaire')])),
                ('resolu', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemes', to='contrats.contrat')),
                ('signale_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemes_signales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ] 